/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{ts,tsx,js,jsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      colors: {
        // Shadcn/ui CSS variable tokens (keep existing)
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // Aero Vitrum / Liquid Glass design tokens
        'av-primary': '#4cd7f6',
        'av-secondary': '#d0bcff',
        'av-tertiary': '#fbabff',
        'av-error': '#ffb4ab',
        'av-background': '#0b1326',
        'av-surface': '#171f33',
        'av-surface-low': '#131b2e',
        'av-surface-high': '#1e2740',
        'av-surface-bright': '#31394e',
        'av-surface-variant': '#2d3449',
        'av-on-surface': '#dbe2fd',
        'av-on-primary': '#001f26',
        'av-outline': '#869397',
        'av-outline-variant': '#3d494c',
        'surface-container-lowest': '#060d20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#1e2740',
        'surface-container-highest': '#252e45',
        'surface-bright': '#31394e',
        'surface-variant': '#2d3449',
        'on-surface': '#dbe2fd',
        'on-surface-variant': '#c0c8e0',
        'on-primary': '#001f26',
        'on-primary-container': '#00424f',
        'on-secondary': '#3c0091',
        'on-secondary-container': '#c4abff',
        'on-tertiary-container': '#6a007a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'on-background': '#dbe2fd',
        'primary-container': '#06b6d4',
        'primary-fixed': '#b8eaff',
        'primary-fixed-dim': '#4cd7f6',
        'secondary-container': '#571bc1',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d0bcff',
        'tertiary-fixed': '#ffd6fd',
        'tertiary-fixed-dim': '#fbabff',
        'error-container': '#93000a',
        'inverse-primary': '#00687a',
        'inverse-surface': '#dbe2fd',
        'surface-tint': '#4cd7f6',
        'surface-dim': '#0b1326',
        'outline': '#869397',
        'outline-variant': '#3d494c',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      backdropBlur: {
        xs: '2px',
      },
      animation: {
        'orb-float': 'orbFloat 8s ease-in-out infinite',
        'orb-float-slow': 'orbFloat 12s ease-in-out infinite reverse',
        'shimmer': 'shimmer 2s linear infinite',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
      },
      keyframes: {
        orbFloat: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(30px, -20px) scale(1.05)' },
          '66%': { transform: 'translate(-20px, 15px) scale(0.97)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '0.6', boxShadow: '0 0 20px rgba(76, 215, 246, 0.3)' },
          '50%': { opacity: '1', boxShadow: '0 0 40px rgba(76, 215, 246, 0.6)' },
        },
      },
    },
  },
  plugins: [],
}
